# -*- coding: utf-8 -*-
"""scrapeZipCodes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uStarXBPh8M0Z3tVUdg0-8HJdHveDQjL
"""

#Jarod Morris
#Senior Project
import requests
from lxml import html
import pandas as pd

def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

link = "https://www.zip-codes.com/state/ca.asp"

pageContent = requests.get(link)
tree = html.fromstring(pageContent.content)
testPath1 = tree.xpath('/')
testPath = tree.xpath('//*[@id="tblZIP"]/tr/td')
df = [x.text_content() for x in testPath]

df = chunks(df, 4)

df = list(df)
columns = df[0]
del df[0]

for pair in df:
  pair[0] = pair[0][-5:]

df = pd.DataFrame(df, columns=columns)
print(df)
df.to_csv()
#print(testPath[0].text_content())